/*By SID*/
CREATE PUBLIC DATABASE LINK "GENEVA"
CONNECT TO apps
IDENTIFIED BY "*****"
USING '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.101.5.200)(PORT = 1521))(CONNECT_DATA = (SID = PRODGEN1)))';